export enum Preset {
  // 운영 일정
  OPERATION_START = "OPERATION_START",
  OPERATION_PRESTART = "OPERATION_PRESTART",
  OPERATION_MAINTENANCE_START = "OPERATION_MAINTENANCE_START",
  OPERATION_MAINTENANCE_END = "OPERATION_MAINTENANCE_END",

  // 모집 일정
  APPLICATION_START = "APPLICATION_START",
  APPLICATION_END = "APPLICATION_END",

  // 지필 일정
  EXAMINATION = "EXAMINATION",

  // 면접 일정
  INTERVIEW = "INTERVIEW",

  ETC = "ETC",
}

export type Schedule = {
  id: string
  title: string
  category: Preset
  startAt: string
}
